// <auto-generated />
namespace SurveyQuesion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aDDING6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aDDING6));
        
        string IMigrationMetadata.Id
        {
            get { return "202406081544533_aDDING6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
